name: ws_mlr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.10
  - pip
  - ipykernel
  - numpy
  - scipy
  - swig # gym dependency
  - moviepy # gym recording wrapper
  - pybullet
  - pip:
    - gymnasium==0.29.1
    - 'stable-baselines3[extra]==2.3.2'
    - rl_zoo3
    - -e submodules/panda-gym