name: ws_mlr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.10
  - pip
  - ipykernel
  - swig # gym dependency
  - moviepy # gym dependency for video recording
  - seaborn # 
  - pip:
    - gymnasium==0.28.1
    - gymnasium[mujoco]
    - 'stable-baselines3[extra]==2.0.0'