name: ws_mlr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.10
  - pip
  - ipykernel
  - numpy
  - scipy
  - swig # gym dependency
  - pybullet
  - pip:
    - gymnasium==0.28.1
    - 'stable-baselines3[extra]==2.0.0'
    - -e external_modules/panda-gym